name: 'atlas-infrastructure-deployment'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

run-name: "${{ github.ref_name }}.${{ github.sha }}.${{ github.workflow }}"

jobs:
  dev-terraform-verify:
    if: ${{ github.event.inputs.environment == 'dev' }}
    uses: ./.github/workflows/terraform-verify.yml
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_DEV_CREDENTIALS }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_DEV_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_DEV_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_DEV_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  dev-terraform-plan:
    if: ${{ github.event.inputs.environment == 'dev' }}
    needs: [dev-terraform-verify]
    uses: ./.github/workflows/terraform-plan.yml
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets:
      atlas-github-token: ${{ secrets.ATLAS_DEV_GITHUB_TOKEN }}
      atlas-sp-secret: ${{ secrets.ATLAS_DEV_SP_SECRET }}
      be-app-secret: ${{ secrets.BE_DEV_APP_SECRET }}
      cliff-secret: ${{ secrets.CLIFF_DEV_SECRET }}
      databricks-clientid: ${{ secrets.DATABRICKS_DEV_CLIENTID }}
      databricks-clientsecret: ${{ secrets.DATABRICKS_DEV_CLIENT_SECRET }}
      dsp-config-git-token: ${{ secrets.DSP_DEV_CONFIG_GIT_TOKEN }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_DEV_CREDENTIALS }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_DEV_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_DEV_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_DEV_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  dev-terraform-apply:
    if: ${{ github.event.inputs.environment == 'dev' }}
    needs: [dev-terraform-plan]
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_DEV_CREDENTIALS }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_DEV_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_DEV_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_DEV_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  qa-terraform-verify:
    if: ${{ always() && github.event.inputs.environment == 'qa' || github.event.inputs.environment == 'qa' && needs.dev-terraform-apply.result == 'success' }}
    needs: [dev-terraform-apply]
    uses: ./.github/workflows/terraform-verify.yml
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_QA_CREDENTIALS }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_QA_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_QA_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_QA_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  qa-terraform-plan:
    if: ${{ always() && (github.event.inputs.environment == 'qa' || needs.qa-terraform-verify.result == 'success') }}
    needs: [qa-terraform-verify]
    uses: ./.github/workflows/terraform-plan.yml
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets:
      atlas-github-token: ${{ secrets.ATLAS_QA_GITHUB_TOKEN }}
      atlas-sp-secret: ${{ secrets.ATLAS_QA_SP_SECRET }}
      be-app-secret: ${{ secrets.BE_QA_APP_SECRET }}
      cliff-secret: ${{ secrets.CLIFF_QA_SECRET }}
      databricks-clientid: ${{ secrets.DATABRICKS_QA_CLIENTID }}
      databricks-clientsecret: ${{ secrets.DATABRICKS_QA_CLIENT_SECRET }}
      dsp-config-git-token: ${{ secrets.DSP_QA_CONFIG_GIT_TOKEN }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_QA_CREDENTIALS }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_QA_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_QA_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_QA_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  qa-terraform-apply:
    if: ${{ always() && (github.event.inputs.environment == 'qa' || needs.qa-terraform-plan.result == 'success') }}
    needs: [qa-terraform-plan]
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_QA_CREDENTIALS }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_QA_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_QA_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_QA_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}


  prod-terraform-verify:
    if: |
      ${{ always() && github.event.inputs.environment == 'prod' || github.event.inputs.environment == 'prod' && needs.qa-terraform-apply.result == 'success'}}
    needs: [qa-terraform-apply]
    uses: ./.github/workflows/terraform-verify.yml
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_PROD_CREDENTIALS }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_PROD_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_PROD_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_PROD_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  prod-terraform-plan:
    if: ${{ always() && (github.event.inputs.environment == 'prod' || needs.prod-terraform-verify.result == 'success') }}
    needs: [prod-terraform-verify]
    uses: ./.github/workflows/terraform-plan.yml
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets:
      atlas-github-token: ${{ secrets.ATLAS_PROD_GITHUB_TOKEN }}
      atlas-sp-secret: ${{ secrets.ATLAS_PROD_SP_SECRET }}
      be-app-secret: ${{ secrets.BE_PROD_APP_SECRET }}
      cliff-secret: ${{ secrets.CLIFF_PROD_SECRET }}
      databricks-clientid: ${{ secrets.DATABRICKS_PROD_CLIENTID }}
      databricks-clientsecret: ${{ secrets.DATABRICKS_PROD_CLIENT_SECRET }}
      dsp-config-git-token: ${{ secrets.DSP_PROD_CONFIG_GIT_TOKEN }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_PROD_CREDENTIALS }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_PROD_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_PROD_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_PROD_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  prod-terraform-apply:
    if: ${{ always() && (github.event.inputs.environment == 'prod' || needs.prod-terraform-plan.result == 'success') }}
    needs: [prod-terraform-plan]
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_PROD_CREDENTIALS }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_PROD_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_PROD_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_PROD_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}